### ISSUE TITLE
Need 64 bit Support

### ISSUE THREAD

**Issue by bjeld** [Everyplay/everyplay-air-sdk#4]
Starting February 1st 2015, Apple will be requiring all new iOS applications submitted to the App Store to include support for 64-bit. http://blogs.adobe.com/flashplayer/2014/10/adobe-air-to-support-upcoming-ios-x64-requirement.html

So Ane should be recompiled to support 64 bit

**Comment by jvihrial** [comment]
Thanks for this information. This is taken to our RnD roadmap now.

**Comment by geretti** [comment]
same requirement here. thanks for putting it together.

**Comment by gomsu** [comment]
Hello guys! Thanks for your interest and feedback. I have now released a version of everyplay.ane that holds also the arm64 binary in it. I'm sorry it took 22d from the issue to do this but my personal roadmap was pretty full. Here's lipo -info from the .a file inside our .ane:

lipo -info META-INF/ANE/iPhone-ARM/libEveryplayAIR.a 
Architectures in the fat file: META-INF/ANE/iPhone-ARM/libEveryplayAIR.a are: armv7 arm64

**Comment by bjeld** [comment]
@gomsu - Fantastic!
Looking so much forward using this in my games!

**Comment by gomsu** [comment]
@bjeld I'm looking forward to see videos of them :). Hoping the best coding moments for you :)

**Comment by geretti** [comment]
thank you! Works like a charm
