### ISSUE TITLE
Still not working in Air Android

### ISSUE THREAD

**Issue by deccosantos** [Everyplay/everyplay-air-sdk#5]
I created a game but this ane is not open in as3 Android version. Everytime when i try to start record or just try to open EveryPlay in my Android Game Version it crashes the app.

How can i solve this?

I think the manifest is wrong in some place because it is not launching everyplay with this manifest in your documentation.

Since now thanks for all

**Comment by rebbTRSi** [comment]
Hello!
Can you please send email to support@everyplay.com with following information:
Phone model
Android version
log from the crash
example project that crashes on that device

We can then lookout what causes these crashes as our test project seems to behave nicely on various Android configurations.
